# Generated by Django 5.1.6 on 2025-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('actividad_ilicita', 'Actividad ilícita'), ('falta_identificacion', 'Falta de identificación'), ('otro', 'Otro')], max_length=50)),
                ('motivo', models.TextField()),
            ],
        ),
    ]
